# Generated by Django 5.1.2 on 2025-04-13 17:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_portfolioitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/')),
            ],
        ),
        migrations.RenameField(
            model_name='portfolioitem',
            old_name='detail_url',
            new_name='project_url',
        ),
        migrations.RemoveField(
            model_name='portfolioitem',
            name='image',
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='client',
            field=models.CharField(default='Default Client', max_length=100),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='images',
            field=models.ManyToManyField(to='main.portfolioimage'),
        ),
    ]
