# Generated by Django 5.1.2 on 2025-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_herosection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
